# This is a basic workflow to help you get started with Actions

name: CI Shared Workflow - Snapshot

# Controls when the workflow will run
on:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pre-checks:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World! Pre Checks OVERRIDDEN_SECRET_1= [ ${{ secrets.OVERRIDDEN_SECRET_1 }} ], CALLER_REPO_SECRET_1= [ ${{ secrets.CALLER_REPO_SECRET_1 }} ]"

  build:
    runs-on: ubuntu-latest
    needs: pre-checks
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install --file pom.xml
      
  post-checks:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: my-step
        run: echo "Hello World! Post Checks"
